os: osx
osx_image: xcode11.5
language: objective-c
xcode_project: Migration.xcodeproj # path to your xcodeproj folder
xcode_scheme: MigrationTests
xcode_scheme: MigrationUITests
xcode_destination: platform=iOS Simulator,OS=13.5,name=iPhone X
