os: osx
osx_image: xcode11.5
language: swift
xcode_project: Migration.xcodeproj # path to your xcodeproj folder
xcode_scheme:
  - MigrationTests
  - MigrationUITests
xcode_destination: platform=iOS Simulator,OS=13.5,name=iPhone X
